version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - perfsprint
    - staticcheck
    - unused
  settings:
    govet:
      disable:
        - tests
    misspell:
      locale: US
    perfsprint:
      int-conversion: true
      err-error: false
      errorf: true
      sprintf1: false
      strconcat: false
    staticcheck:
      checks:
        - -ST1000
        - -ST1005
        - all
      
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
    gofmt:
      simplify: true
